sudo: required
language: csharp
solution: api-client-shared.sln
mono: none
git:
  submodules: false
dotnet: 2.1.502
before_install:
  # Change github url to https for submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

  # Decrypt private key used for tests
  - openssl aes-256-cbc -K $encrypted_3afad0b3f334_key -iv $encrypted_3afad0b3f334_iv -in Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12.enc -out Bring_Digital_Signature_Key_Encipherment_Data_Encipherment.p12 -d

  - ./travis-deploy/patch-assembly-version.sh Directory.Build.props $TRAVIS_TAG

install:
  - dotnet restore

script:
  - set -e #Makes sure we get a fail fast if some of the scripts fails

  # Build
  - dotnet build -c Release

  # Setup
  - ./travis-deploy/add-secrets.sh
  - find /home/travis/.microsoft
  - cat /home/travis/.microsoft/usersecrets/organization-certificate/secrets.json

  # Test
  - dotnet test Digipost.Signature.Api.Client.Direct.Tests/Digipost.Signature.Api.Client.Direct.Tests.csproj
  - dotnet test Digipost.Signature.Api.Client.Core.Tests/Digipost.Signature.Api.Client.Core.Tests.csproj
  - dotnet test Digipost.Signature.Api.Client.Portal.Tests/Digipost.Signature.Api.Client.Portal.Tests.csproj

deploy:
  skip_cleanup: true
  provider: script
  script: ./travis-deploy/pack-and-push.sh $TRAVIS_TAG $NUGET_API_KEY $TRAVIS_BUILD_DIR Digipost.Signature.Api.Client.Core Digipost.Signature.Api.Client.Direct Digipost.Signature.Api.Client.Portal Digipost.Signature.Api.Client.Resources Digipost.Signature.Api.Client.Scripts
  on:
    tags: true
