# name of the software
name: .NET client library for Digipost signature Api

# url of the download button
downloadUrl: https://www.nuget.org/packages/digipost-signature-api-client/

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

baseurl: "/signature-api-client-dotnet"

currentVersion: "1.7"
versions: ["1.7", "1.6", "1.5", "1.4"]

collections:
  v1_4:
    output: true
    permalink: /v1.4/
  v1_5:
    output: true
    permalink: /v1.5/
  v1_6:
    output: true
    permalink: /v1.6/
  v1_7:
    output: true
    permalink: /v1.7/

# list of additional links on the right of the top menu
headerLinks:
  - title: Download library
    url: https://www.nuget.org/packages/digipost-signature-api-client/
  - title: GitHub
    url: https://github.com/digipost/signature-api-client-dotnet
  - title: Digipost
    url: https://www.digipost.no

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/digipost/signature-api-client-dotnet
  - title: Issues
    url: https://github.com/digipost/signature-api-client-dotnet/issues

# header
header:
  color1: "#e32d22"
  color2:
  trianglify: false

# github buttons
githubButton:
  user: digipost
  repo: signature-api-client-dotnet

# twitter buttons
twitter:
  enabled: true
  via:
  hash:
  account: digipost_no

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-77734017-1
  domain: auto

# DON'T MODIFY
highlight: rouge

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
